### ISSUE TITLE
The globe of the world does not load

### ISSUE THREAD

**Issue by dcapeletti** [Gaia3D/mago3djs#614]
Hi,
I just installed mago3d and loaded the test models but in the browser I can't see the globe of the earth. How can I solve it?
I attach images to see if you can help me.

Thank you
![2018-10-11_16-02-50](https://user-images.githubusercontent.com/5890886/46827537-32ac0b80-cd6f-11e8-9c99-0ae8e60bb9aa.png)
![chrome_2018-10-11_16-04-38](https://user-images.githubusercontent.com/5890886/46827594-625b1380-cd6f-11e8-9700-bd890daa193c.png)

**Comment by shire75** [comment]
Hi.
This issue is caused by authority checking/filtering by the AGI terrain server.
(AGI, the manufacturer of Cesium, has changed their policy on the terrain server after launching Cesium ION recently.)

So you have to turn off the terrain data to see the globe.
To do this, go along following steps.

1. Click the button where you can change image/terrain providing server.
![image](https://user-images.githubusercontent.com/13214937/46841533-86683480-ce03-11e8-9c0f-73d56f56a1cc.png)

2. Select 'WGS84 Ellipsoid' in Terrain category.
![image](https://user-images.githubusercontent.com/13214937/46841569-c8917600-ce03-11e8-9c23-d538ac71bbd1.png)

Thanks.

**Comment by dcapeletti** [comment]
Hi, the problem has been solved. 

I wonder if I can apply this change with some JavaScript instruction when loading the page, as it is more useful to me. If you could give me a hint of some instruction, it will be of great help.

Thank you

**Comment by dcapeletti** [comment]
Hello, I've already solved it by changing:
`"geo_init_default_terrain": "WGS84 Ellipsoid",`
in the archive workshop-policy-cesium.json

Greetings
